//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Actions/DefaultControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DefaultControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DefaultControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultControls"",
    ""maps"": [
        {
            ""name"": ""Default Action Map"",
            ""id"": ""20a300b0-dca5-4c18-bb0c-f28c415d0570"",
            ""actions"": [
                {
                    ""name"": ""toggleScreenShake"",
                    ""type"": ""Button"",
                    ""id"": ""59cc860f-5a5f-41ef-83bd-222fbe62b7ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleAudio"",
                    ""type"": ""Button"",
                    ""id"": ""26c5f80e-7215-454f-b3bb-2f0f3915e9b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleScreenFlash"",
                    ""type"": ""Button"",
                    ""id"": ""7ff4340b-f15d-4fec-9e55-c372b93b11e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleHitStop"",
                    ""type"": ""Button"",
                    ""id"": ""5a1329c9-9ba4-4b76-ad7a-bb8e5e4bd5d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleBulletTime"",
                    ""type"": ""Button"",
                    ""id"": ""9829a7fc-2e44-41e7-92d4-a65522253b3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleParticles"",
                    ""type"": ""Button"",
                    ""id"": ""bf185403-d547-450f-9a45-d7fdb63078e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleImpactFlash"",
                    ""type"": ""Button"",
                    ""id"": ""b5a998cc-f0d6-47d0-9986-2e567b7dd9a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleTrails"",
                    ""type"": ""Button"",
                    ""id"": ""321300dc-f2e7-4c7a-96ac-889e74c93791"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleForeverTrails"",
                    ""type"": ""Button"",
                    ""id"": ""c24de540-3015-4c20-85c5-7d23bf0c3659"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6592f0c7-e0b6-49ae-bfd8-9fcfcf86e104"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleScreenShake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8a5ae79-38ed-4647-aa37-4c29cca0a1f9"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleAudio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f806ae0-d24a-4d20-9c2e-e8fdfe3472b3"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleScreenFlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43befb73-5d2a-4707-9e09-4ee9dda0e669"",
                    ""path"": ""<Keyboard>/#(F)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleHitStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eb89e10-9d39-4c78-b5bb-f15c68371dcc"",
                    ""path"": ""<Keyboard>/#(G)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleBulletTime"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a57c0c2f-03cb-4a8e-9054-ddbc222596da"",
                    ""path"": ""<Keyboard>/#(H)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleParticles"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""756eb2a3-2384-40a9-aef1-5644bc3a9205"",
                    ""path"": ""<Keyboard>/#(J)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleImpactFlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7faa8789-52a5-4b66-a104-d7c1e0d7d019"",
                    ""path"": ""<Keyboard>/#(K)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleTrails"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8b5234f-56c2-4c9e-8d3c-fa397ffdbd4e"",
                    ""path"": ""<Keyboard>/#(L)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleForeverTrails"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default Action Map
        m_DefaultActionMap = asset.FindActionMap("Default Action Map", throwIfNotFound: true);
        m_DefaultActionMap_toggleScreenShake = m_DefaultActionMap.FindAction("toggleScreenShake", throwIfNotFound: true);
        m_DefaultActionMap_toggleAudio = m_DefaultActionMap.FindAction("toggleAudio", throwIfNotFound: true);
        m_DefaultActionMap_toggleScreenFlash = m_DefaultActionMap.FindAction("toggleScreenFlash", throwIfNotFound: true);
        m_DefaultActionMap_toggleHitStop = m_DefaultActionMap.FindAction("toggleHitStop", throwIfNotFound: true);
        m_DefaultActionMap_toggleBulletTime = m_DefaultActionMap.FindAction("toggleBulletTime", throwIfNotFound: true);
        m_DefaultActionMap_toggleParticles = m_DefaultActionMap.FindAction("toggleParticles", throwIfNotFound: true);
        m_DefaultActionMap_toggleImpactFlash = m_DefaultActionMap.FindAction("toggleImpactFlash", throwIfNotFound: true);
        m_DefaultActionMap_toggleTrails = m_DefaultActionMap.FindAction("toggleTrails", throwIfNotFound: true);
        m_DefaultActionMap_toggleForeverTrails = m_DefaultActionMap.FindAction("toggleForeverTrails", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default Action Map
    private readonly InputActionMap m_DefaultActionMap;
    private List<IDefaultActionMapActions> m_DefaultActionMapActionsCallbackInterfaces = new List<IDefaultActionMapActions>();
    private readonly InputAction m_DefaultActionMap_toggleScreenShake;
    private readonly InputAction m_DefaultActionMap_toggleAudio;
    private readonly InputAction m_DefaultActionMap_toggleScreenFlash;
    private readonly InputAction m_DefaultActionMap_toggleHitStop;
    private readonly InputAction m_DefaultActionMap_toggleBulletTime;
    private readonly InputAction m_DefaultActionMap_toggleParticles;
    private readonly InputAction m_DefaultActionMap_toggleImpactFlash;
    private readonly InputAction m_DefaultActionMap_toggleTrails;
    private readonly InputAction m_DefaultActionMap_toggleForeverTrails;
    public struct DefaultActionMapActions
    {
        private @DefaultControls m_Wrapper;
        public DefaultActionMapActions(@DefaultControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @toggleScreenShake => m_Wrapper.m_DefaultActionMap_toggleScreenShake;
        public InputAction @toggleAudio => m_Wrapper.m_DefaultActionMap_toggleAudio;
        public InputAction @toggleScreenFlash => m_Wrapper.m_DefaultActionMap_toggleScreenFlash;
        public InputAction @toggleHitStop => m_Wrapper.m_DefaultActionMap_toggleHitStop;
        public InputAction @toggleBulletTime => m_Wrapper.m_DefaultActionMap_toggleBulletTime;
        public InputAction @toggleParticles => m_Wrapper.m_DefaultActionMap_toggleParticles;
        public InputAction @toggleImpactFlash => m_Wrapper.m_DefaultActionMap_toggleImpactFlash;
        public InputAction @toggleTrails => m_Wrapper.m_DefaultActionMap_toggleTrails;
        public InputAction @toggleForeverTrails => m_Wrapper.m_DefaultActionMap_toggleForeverTrails;
        public InputActionMap Get() { return m_Wrapper.m_DefaultActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionMapActionsCallbackInterfaces.Add(instance);
            @toggleScreenShake.started += instance.OnToggleScreenShake;
            @toggleScreenShake.performed += instance.OnToggleScreenShake;
            @toggleScreenShake.canceled += instance.OnToggleScreenShake;
            @toggleAudio.started += instance.OnToggleAudio;
            @toggleAudio.performed += instance.OnToggleAudio;
            @toggleAudio.canceled += instance.OnToggleAudio;
            @toggleScreenFlash.started += instance.OnToggleScreenFlash;
            @toggleScreenFlash.performed += instance.OnToggleScreenFlash;
            @toggleScreenFlash.canceled += instance.OnToggleScreenFlash;
            @toggleHitStop.started += instance.OnToggleHitStop;
            @toggleHitStop.performed += instance.OnToggleHitStop;
            @toggleHitStop.canceled += instance.OnToggleHitStop;
            @toggleBulletTime.started += instance.OnToggleBulletTime;
            @toggleBulletTime.performed += instance.OnToggleBulletTime;
            @toggleBulletTime.canceled += instance.OnToggleBulletTime;
            @toggleParticles.started += instance.OnToggleParticles;
            @toggleParticles.performed += instance.OnToggleParticles;
            @toggleParticles.canceled += instance.OnToggleParticles;
            @toggleImpactFlash.started += instance.OnToggleImpactFlash;
            @toggleImpactFlash.performed += instance.OnToggleImpactFlash;
            @toggleImpactFlash.canceled += instance.OnToggleImpactFlash;
            @toggleTrails.started += instance.OnToggleTrails;
            @toggleTrails.performed += instance.OnToggleTrails;
            @toggleTrails.canceled += instance.OnToggleTrails;
            @toggleForeverTrails.started += instance.OnToggleForeverTrails;
            @toggleForeverTrails.performed += instance.OnToggleForeverTrails;
            @toggleForeverTrails.canceled += instance.OnToggleForeverTrails;
        }

        private void UnregisterCallbacks(IDefaultActionMapActions instance)
        {
            @toggleScreenShake.started -= instance.OnToggleScreenShake;
            @toggleScreenShake.performed -= instance.OnToggleScreenShake;
            @toggleScreenShake.canceled -= instance.OnToggleScreenShake;
            @toggleAudio.started -= instance.OnToggleAudio;
            @toggleAudio.performed -= instance.OnToggleAudio;
            @toggleAudio.canceled -= instance.OnToggleAudio;
            @toggleScreenFlash.started -= instance.OnToggleScreenFlash;
            @toggleScreenFlash.performed -= instance.OnToggleScreenFlash;
            @toggleScreenFlash.canceled -= instance.OnToggleScreenFlash;
            @toggleHitStop.started -= instance.OnToggleHitStop;
            @toggleHitStop.performed -= instance.OnToggleHitStop;
            @toggleHitStop.canceled -= instance.OnToggleHitStop;
            @toggleBulletTime.started -= instance.OnToggleBulletTime;
            @toggleBulletTime.performed -= instance.OnToggleBulletTime;
            @toggleBulletTime.canceled -= instance.OnToggleBulletTime;
            @toggleParticles.started -= instance.OnToggleParticles;
            @toggleParticles.performed -= instance.OnToggleParticles;
            @toggleParticles.canceled -= instance.OnToggleParticles;
            @toggleImpactFlash.started -= instance.OnToggleImpactFlash;
            @toggleImpactFlash.performed -= instance.OnToggleImpactFlash;
            @toggleImpactFlash.canceled -= instance.OnToggleImpactFlash;
            @toggleTrails.started -= instance.OnToggleTrails;
            @toggleTrails.performed -= instance.OnToggleTrails;
            @toggleTrails.canceled -= instance.OnToggleTrails;
            @toggleForeverTrails.started -= instance.OnToggleForeverTrails;
            @toggleForeverTrails.performed -= instance.OnToggleForeverTrails;
            @toggleForeverTrails.canceled -= instance.OnToggleForeverTrails;
        }

        public void RemoveCallbacks(IDefaultActionMapActions instance)
        {
            if (m_Wrapper.m_DefaultActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActionMapActions @DefaultActionMap => new DefaultActionMapActions(this);
    public interface IDefaultActionMapActions
    {
        void OnToggleScreenShake(InputAction.CallbackContext context);
        void OnToggleAudio(InputAction.CallbackContext context);
        void OnToggleScreenFlash(InputAction.CallbackContext context);
        void OnToggleHitStop(InputAction.CallbackContext context);
        void OnToggleBulletTime(InputAction.CallbackContext context);
        void OnToggleParticles(InputAction.CallbackContext context);
        void OnToggleImpactFlash(InputAction.CallbackContext context);
        void OnToggleTrails(InputAction.CallbackContext context);
        void OnToggleForeverTrails(InputAction.CallbackContext context);
    }
}
